version: '3'

services:
  usermanagementsystem:
    build: usermanagementsystem
    mem_limit: 512m
    ports:
      - "1010:1010"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/cap_user?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: root
    restart: always

  mysql:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cap_user
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
